language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jensborch-github"
jdk:
  - openjdk8
script:
  - ././mvnw verify sonar:sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'