language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jensborch-github"
jdk:
  - openjdk8
before_install:
  gradle wrapper --gradle-version 6.0
script:
  - ./gradlew build jacocoTestReport
  - ./gradlew sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'