openapi: 3.0.1
info:
  title: Webhooks4j
  description: Small, simple and extendable Java library for messaging using webhooks.
  version: v1
paths:
  /publisher-events/{id}:
    get:
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEventStatus'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /publisher-events:
    get:
      operationId: list
      parameters:
      - name: topics
        in: query
        schema:
          type: string
      - name: webhook
        in: query
        schema:
          type: string
      - name: from
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebhookEventStatus'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /publisher-webhooks/{id}:
    get:
      operationId: get_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    delete:
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /publisher-webhooks:
    get:
      operationId: list_1
      parameters:
      - name: topics
        in: query
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    post:
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Webhook'
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /subscriber-events/{id}:
    get:
      operationId: get_2
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookEventStatus'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /subscriber-events:
    get:
      operationId: list_2
      parameters:
      - name: topics
        in: query
        schema:
          type: string
      - name: webhook
        in: query
        schema:
          type: string
      - name: from
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebhookEventStatus'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    post:
      operationId: receive
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEvent'
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /subscriber-webhooks/{id}:
    get:
      operationId: get_3
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webhook'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    put:
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Webhook'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    delete:
      operationId: delete_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
  /subscriber-webhooks:
    get:
      operationId: list_3
      parameters:
      - name: topics
        in: query
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Webhook'
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
    post:
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Webhook'
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookError'
components:
  schemas:
    WebhookEvent:
      required:
      - data
      - id
      - topic
      type: object
      properties:
        id:
          type: string
          format: uuid
        webhook:
          type: string
          format: uuid
        topic:
          type: string
        data:
          type: object
          additionalProperties:
            type: object
    WebhookEventStatus:
      required:
      - event
      - id
      - start
      - status
      type: object
      properties:
        id:
          type: string
          format: uuid
        event:
          $ref: '#/components/schemas/WebhookEvent'
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - STARTED
          - FAILED
          - SUCCESS
    WebhookError:
      required:
      - code
      - detail
      - status
      - title
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: string
          enum:
          - AUTHORIZATION_ERROR
          - AUTHENTICATION_ERROR
          - VALIDATION_ERROR
          - UNKNOWN_PUBLISHER
          - UNKNOWN_ERROR
          - REGISTER_ERROR
          - NOT_FOUND
          - SYNC_ERROR
          - ILLEGAL_STATUS
        title:
          type: string
        details:
          type: string
          writeOnly: true
        detail:
          type: string
    Webhook:
      required:
      - created
      - id
      - publisher
      - state
      - subscriber
      - topics
      - updated
      type: object
      properties:
        id:
          type: string
          format: uuid
        publisher:
          type: string
          format: uri
        subscriber:
          type: string
          format: uri
        state:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
          - SUBSCRIBE
          - SUBSCRIBING
          - SYNCHRONIZE
          - SYNCHRONIZING
          - UNSUBSCRIBE
          - UNSUBSCRIBING
          - FAILED
        topics:
          maxItems: 2147483647
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
