name: "Dependabot Automerge"

on:
  workflow_call:

jobs:
  automerge:
    uses: jensborch/workflows/.github/workflows/dependabot-automerge.yml.yml@main
    permissions:
      pull-requests: write
      contents: write
    secrets: inherit
