name: "Dependabot Automerge"

on:
  pull_request:
    branches: [master]

jobs:
  automerge:
    uses: jensborch/workflows/.github/workflows/dependabot-automerge.yml@main
    permissions:
      pull-requests: write
      contents: write
    secrets: inherit
