name: Pull Request

on:
  pull_request:
    branches: [ master ]    

jobs:
  maven:
    uses: ./.github/workflows/maven.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  automerge:
    needs: maven
    uses: ./.github/workflows/automerge.yml
