name: Release

on:
  push:
    branches:
      - "release/**"

jobs:
  call-workflow:
    uses: jensborch/workflows/.github/workflows/release-release.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      java-version: 11
